version: "3.7"

services:       
  nodejs:
    build: .
    image: ismf/basic-api:v1.0
    container_name: ismf_node
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PUERTO_HTTP: "8080"
      LOG_LEVEL: "TRACE"
      

